title: Eduardo Albertos
email: albertos.eduardo@gmail.com
description: Eduardo Albertos Software Developer
baseurl: ""
url: ""
github_username: ealbertos

theme: jekyll-theme-slate 
plugins:
  - jekyll-feed
